Dashboard/urls.py
from django.urls import path

from Dashboard import views

app_name = 'Dashboard'
urlpatterns = [
    path('', views.Home, name='Home'),
    path('section/<str:sec>', views.section, name='section'),
    path('filter', views.productsfilter, name='filter'),
    path('search', views.search, name='search'),
    path('Maptest', views.Maptest,name='Maptest')
]

ManageProduct/urls.py
from django.urls import path

from . import views
from .views import ProductAdmin ,ProductsCustomer

app_name = 'ManageProduct'
urlpatterns = [

    # path('ProductList/', ProductAdmin.view_all_products, name='view_all_products'),
    path('ProductCreate/', ProductAdmin.product_create, name='product_create'),
    path('ProductView/<int:pk>', ProductAdmin.product_view, name='product_view'),
    path('ProductUpdate/<int:pk>', ProductAdmin.update_product, name='update_product'),
    path('ProductDelete/<int:pk>', ProductAdmin.delete_product, name='delete_product'),
    # path('profilter/', views.profilter, name='profilter'),
    path('add_to_favorite/<int:id>', ProductsCustomer.add_to_favorite, name='add_to_favorite'),
    path('remove_to_favorite/<int:id>', ProductsCustomer.remove_to_favorite, name='remove_to_favorite'),

]

ManageStore/urls.py
from django.urls import path

from ManageStore import views

app_name = 'ManageStore'
urlpatterns = [

    path('Store/Detail/<int:store_id>', views.view_store, name='view_store'),
    path('Store/Detail/<int:store_id>/<str:section>', views.products_in_section, name='view_store_section'),
    path('Store/Create', views.create_store, name='create_store'),
    path('Edit/Store/Detail', views.edit_store, name='edit_store'),
    path('add/ad_img/', views.add_ADs, name='add_ADs'),
    path('delete/ad_img/<int:ad_id>', views.delete_ADs, name='delete_ADs'),


]

Project/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Shopping_Cart/', include('ShoppingCart.urls', namespace='ShoppingCart')),
    path('', include('Dashboard.urls', namespace='Dashboard')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('ManageProduct/', include('ManageProduct.urls', namespace='ManageProduct')),
    path('ManageStore/', include('ManageStore.urls', namespace='ManageStore')),
    path('ManageOffer/', include('ManageOffer.urls', namespace='ManageOffer')),
    path('ManageReview/', include('ManageReview.urls', namespace='ManageReview')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'Dashboard.views.error_404'

ShoppingCart/urls.py
from django.urls import path

from ShoppingCart import ShoppingCartView as view

app_name = "ShoppingCart"

urlpatterns = [

    path('viwe', view.view_shopping_cart, name='view_shopping_cart'),
    path('add/product/<int:product_id>/quantity/<int:quantity>', view.add_product_to_cart, name='add_product_to_cart'),
    path('edit/product/<int:product_id>/quantity/<int:quantity>', view.edit_product_quantity_cart,
         name='edit_product_quantity_cart'),
    path('add/product/<int:product_id>/quantity/<int:quantity>', view.add_offer_to_cart, name='add_offer_to_cart'),
    path('edit/product/<int:CartOffer_id>/quantity/<int:quantity>', view.edit_offer_quantity_cart,
         name='edit_offer_quantity_cart'),

    path('test/', view.mainUseCase, name='mainUseCase')

]

ManageProduct/models.py
from django.core.validators import MinValueValidator
from django.db import models
from django.utils.text import slugify

from ManageReview.models import Review

SECTIONS = (
    ('Fruit', 'Fruit'),
    ('Veggies', 'Veggies'),
    ('Seafood', 'Seafood'),
    ('Meat', 'Meat'),
    ('Cereal', 'Cereal'),
    ('Condiments', 'Condiments'),
    ('Baby', 'Baby'),
    ('Pet', 'Pet'),
    ('Paper', 'Paper'),
    ('Dairy', 'Dairy'),
    ('Frozen', 'Frozen')
)

TYPE = (
    ('anonymous', 'anonymous'),
    ('Fresh Food', 'Fresh Food'),
    ('Food Cupboard', 'Food Cupboard'),
    ('Frozen Food', 'Frozen Food'),
    ('Beverages', 'Beverages'),
    ('Bio & Organic Food', 'Bio & Organic Food'),
    ('Baby Product', 'Baby Product'),
    ('Cleaning & Household', 'Cleaning & Household'),
    ('Health & Fitness', 'Health & Fitness'),
    ('Smartphones, Tablets & Wearables', 'Smartphones, Tablets & Wearables'),
    ('Electronics & Appliances', 'Electronics & Appliances'),
    ('Home & Garden', 'Home & Garden'),
    ('Pet Supplies ', 'Pet Supplies '),
    ('Toys & OutDoor', 'Toys & OutDoor'),
    ('Stationery & School Supplies', 'Stationery & School Supplies'),
    ('Kiosk', 'Kiosk'),
    ('Automotive', 'Automotive'),
)
MANUFACTURERS = (
    ('Manufacturer 1', 'Manufacturer 1'),
    ('Manufacturer 2', 'Manufacturer 2')
)

choices = SECTIONS


class Product(models.Model):
    name = models.CharField(max_length=50, null=False)
    product_sections = models.CharField(max_length=50 ,blank=False)
    slug = models.SlugField(blank=True, null=True)
    price = models.FloatField(validators=[MinValueValidator(0.0)], default=1.0)
    type = models.CharField(max_length=50, null=False, choices=TYPE)
    number_Of_Copy = models.PositiveIntegerField(blank=True, null=True)
    par_Code = models.CharField(max_length=50, blank=True, null=True)
    description = models.TextField(max_length=500, blank=True, null=True)
    manufacturer = models.CharField(max_length=50, choices=MANUFACTURERS, default='anonymous Manufacturer')
    # image = ResizedImageField(size=[662, 654], upload_to='Product/img/%Y-%m-%d/', default='Product default.png')
    image = models.ImageField(upload_to='Products', default='Product default.png')
    discount = models.FloatField(validators=[MinValueValidator(0.0)], default=1.0)
    ProductReview = models.ManyToManyField(Review, blank=True)

    class Meta:
        ordering = ["price"]

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        if not self.price:
            self.price = (self.price * self.discount)

        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        self.price = self.price * self.discount
        return str(self.name)

    @property
    def average_review(self):
        revs = self.ProductReview.all()

        if revs:
            total = 0
            for x in revs:
                total += x.rating
            return (total / len(revs)) * 20
        else:
            return 0

    def grt_price_after_discount(self):
        return self.price - (self.discount / 100 * self.price)

ManageStore/models.py
import datetime

from django.db import models
from django.utils.text import slugify
from phonenumber_field.modelfields import PhoneNumberField

from ManageOffer.models import Offer
from ManageProduct.models import Product
from ManageReview.models import Review

STORE_TYPE = (
    ('HyperMarket', 'HyperMarket'),
    ('BigMarket', 'BigMarket')
)


class Section(models.Model):
    name = models.CharField(max_length=20, blank=True)

    def __str__(self):
        return str(self.name)


class AD_imags(models.Model):

    def AD_imags_directory_path(instance, filename):
        return 'AD_imags/{0}/{1}'.format(instance.name, filename)

    name = models.CharField(max_length=50)
    ad_imags = models.ImageField(upload_to=AD_imags_directory_path, default='AD default.png')


class Store(models.Model):
    def store_directory_path(instance, filename):
        return 'Store/{0}-{1}'.format((instance.name, instance.id), filename)

    sections = models.ManyToManyField(Section, blank=True)
    slug = models.SlugField(blank=True, null=True)
    name = models.CharField(max_length=50, unique=True, null=False)
    image = models.ImageField(upload_to=store_directory_path, default='store default.jpg')
    phonesNumber = PhoneNumberField(null=True, blank=True, unique=True,
                                    help_text='Phone number must be entered in the format \'+999999999\'. Up to 15 digits allowed.')
    type = models.CharField(max_length=50, choices=STORE_TYPE, default='HyperMarket')
    url = models.URLField(max_length=200, blank=True, unique=True, null=True)
    description = models.TextField(max_length=500, blank=True, null=True)
    start_hours = models.TimeField(max_length=50, blank=True, null=True)
    close_hours = models.TimeField(max_length=50, blank=True, null=True)
    state = models.BooleanField(default=True, blank=True)
    join_at = models.DateField(null=True, blank=True)
    products = models.ManyToManyField(Product, blank=True)
    StoreReviews = models.ManyToManyField(Review, blank=True)
    StoreOffers = models.ManyToManyField(Offer, blank=True)
    new = models.BooleanField(default=True, null=False)
    ADs = models.ManyToManyField(AD_imags)

    def get_ADs_id(self):
        IDs = []
        for ad in self.ADs.all():
            IDs.append(ad.id)
        return IDs

    def save(self, *args, **kwargs):
        if not self.name:
            self.name = ('NO NAME {0}'.format(datetime.datetime.now()))
        if not self.slug:
            self.slug = slugify(self.name)
        # if not self.ADs:
        #     self.ADs= AD_imags.objects.create(mane='{0}-{1}'.format(self.name,self.id))
        super(Store, self).save(*args, **kwargs)

    @property
    def is_open_now(self):
        if (self.close_hours and self.start_hours) is not None:
            now = datetime.datetime.now().time()
            self.state = self.start_hours <= now <= self.close_hours
            return self.state

    def __str__(self):
        self.is_open_now
        return str(self.name)

    @property
    def Average(self):
        if self.StoreReviews.all():
            revs = self.StoreReviews.all()
            total = 0
            for x in revs:
                total += x.rating
            return total / len(revs)
        else:
            return 0

    def get_sections(self):
        return self.sections.all()

    def is_sections_exist(self, sec):
        for name in self.sections.all():
            if name.name == sec:
                return True
        return False

    def add_sections(self, new_sections):
        sec = Section(name=new_sections)
        sec.save()
        self.sections.add(sec)
        self.save()

ManageProduct/forms.py
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):
    # sections = forms.CharField(max_length=20)

    class Meta:
        model = Product
        fields = ['name',
                  'price',
                  'image',
                  'type',
                  'discount',
                  'manufacturer',
                  'number_Of_Copy',
                  'par_Code',
                  ]
    def sec(self, sec_list):
        self.sections = forms.CharField(widget=forms.Select(choices=[(sec, sec) for sec in sec_list]),max_length=20)
        self.fields['sections'] = self.sections

ManageProduct/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse, JsonResponse, HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404
from ManageReview.forms import ReviewForm
from accounts.CustomerProfilemodel import CustomerProfile
from accounts.models import StoreAdminProfile
from .forms import ProductForm
from .models import Product


class ProductsCustomer():
    def add_to_favorite(request, id, ):
        user = get_object_or_404(CustomerProfile, user=request.user)
        product = get_object_or_404(Product, id=id)
        user.favorite.add(product)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    def remove_to_favorite(request, id):
        user = get_object_or_404(CustomerProfile, user=request.user)
        p = Product.objects.get(id=id)
        user.favorite.remove(p)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class ProductAdmin():

    def product_view(request, pk):
        product = get_object_or_404(Product, pk=pk)
        form = ReviewForm()
        return render(request, 'product_home.html', {'product': product, 'form': form})

    @login_required(login_url='accounts:login')
    def product_create(request):
        try:
            StorAdmin = get_object_or_404(StoreAdminProfile, user=request.user)
            if request.method == 'POST':
                form = ProductForm(request.POST or None, request.FILES or None)
                if form.is_valid():

                    var = Product.objects.create(
                        name=request.POST['name'],
                        price=request.POST['price'],
                        type=request.POST['type'],
                        discount=request.POST['discount'],
                        manufacturer=request.POST['manufacturer'],
                        number_Of_Copy=request.POST['number_Of_Copy'],
                        par_Code=request.POST['par_Code'],
                        product_sections=request.POST['sections'],
                        image=request.FILES['image']
                    )
                    StorAdmin.store.products.add(var)
                    messages.success(request, 'Add product Done.')
                    return redirect('accounts:StoreAdminProfileView')
            else:
                Stor_sections = StorAdmin.store.sections.all()
                sec_list = [sec.name for sec in Stor_sections]
                form = ProductForm()
                form.sec(sec_list=sec_list)
            return render(request, 'product_add_form.html', {'form': form})
        except:
            messages.warning(request,"Make Sure That All Data Is Entered And Correct...!")
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    def update_product(request, pk):
        StorAdmin = get_object_or_404(StoreAdminProfile, user=request.user)
        print(StorAdmin)
        product = get_object_or_404(Product, pk=pk)
        if StorAdmin.store.products.get(pk=pk):
            if request.method == 'POST':
                form = ProductForm(request.POST or None, request.FILES or None, instance=product)
                if form.is_valid():
                    edit = form.save(commit=False)
                    edit.save()
                return redirect('accounts:StoreAdminProfileView')
            else:
                form = ProductForm(instance=product)
                Stor_sections = StorAdmin.store.sections.all()
                print(type(Stor_sections))
                sec_list = [sec.name for sec in Stor_sections]
                form.sec(sec_list=sec_list)
            return render(request, 'product_add_form.html', {'form': form})
        else:
            return Http404

    def delete_product(request, pk):
        StorAdmin = get_object_or_404(StoreAdminProfile, user=request.user)
        product = get_object_or_404(Product, pk=pk)
        if StorAdmin.store.products.get(pk=pk):
            if request.method == 'POST':
                name = product.name
                # StorAdmin.store.products.remove(product)
                obj = get_object_or_404(Product, pk=pk)
                obj.delete()
                messages.success(request, 'Product {0} Delete Done'.format(name))
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

ManageProduct/templates/filter.html
{% load bootstrap5 %}
{% block Search %}
    <div class="container">
        <div class="row ">
            <div class="col-sm-12 col-md-12 col-lg-12 card" align="centre">
                <form method="GET" action="{% url 'Dashboard:filter' %}">
                    <div class="row ">
                        <div class="col-sm-3 col-md-3 col-lg-3">{% bootstrap_field myfilter.form.name %}</div>
                        <div class="col-sm-3 col-md-3 col-lg-3">{% bootstrap_field myfilter.form.type %}</div>
                        <div class="col-sm-3 col-md-3 col-lg-3">{% bootstrap_field myfilter.form.description %}</div>
                        <div class="col-sm-3 col-md-3 col-lg-3">{% bootstrap_field myfilter.form.manufacturer %}</div>
                    </div>
                    <div align="center">
                       <br></be> <button type="submit" class="btn btn-success">Search</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock Search %}

ManageProduct/templates/product_add_form.html
{% extends "base.html" %}
{% load bootstrap5 %}

{% block content %}
        <title>Edit Product</title>

    <div class="container">

        <h1>Product Edit</h1>
        <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <br><input type="submit" value="Submit"/>
        </form>
    </div>



{% endblock content %}

ManageProduct/templates/product_card.html
{% block product_card %}
    <div class="container">
        <div class="row">
            <div class="card mb-1">
                <div class="row md-1">
                    <div class="col-md-3">
                        <img class="img-fluid" src="{{ product.image.url }}" alt="" style="height: 300px;width: 300px">
                    </div>
                    <div class="col-md-9">
                        <div class="card-body">
                            <div class="card-title "><a href="#"><b>{{ product }}</b></a></div>
                            <p class="card-text">

                            <p><b>Product Details</b></p>


                            <div class="row">
                                <div class="col-6">
                                    <br><small><b>Price :</b>{{ product.price }}$</small>
                                    <br><small><b> type :</b>{{ product.type }}</small>
                                    <br><small><b> Discount:</b>{{ product.discount }}%</small>
                                    <br><small><b> Description:</b>{{ product.description|slice:'50' }}</small>
                                </div>
                                <div class="col-6">
                                    <br><small><b> Copy's :</b>{{ product.number_Of_Copy }}# copy </small>
                                    <br><small><b> Sections:</b>{{ product.product_sections }}</small>
                                    <br><small><b> Par Code :</b>{{ product.par_Code }} </small>
                                    <br><small><b> manufacturer :</b>{{ product.manufacturer }}</small>
                                </div>
                            </div>


                            <div class="col align-self-end">
                                {% if request.user.customerprofile %}
                                       {% if product.store_set.first.id %}
                                            <a href="{% url 'ManageStore:view_store' product.store_set.first.id %}"><img
                                                    src="{{ product.store_set.first.image.url }}" alt="" height="40"
                                                    width="40"
                                                    style="position: marker; bottom: 10px; right: 10px;"></a>
                                        {% endif %}
                                    {% if product.id in  request.user.customerprofile.cart.get_product_ids %}
                                        <a class="btn btn-danger"
                                           href="{% url 'ShoppingCart:edit_product_quantity_cart' product.id 0 %}">remove </a>
                                    {% else %}
                                        <a class="btn btn-success"
                                           href="{% url 'ShoppingCart:add_product_to_cart' product.id 1 %}"> add</a>
                                    {% endif %}
                                    {% if product.id in  request.user.customerprofile.get_Customer_Favorite_IDs %}
                                        <a href="{% url 'ManageProduct:remove_to_favorite' product.pk %}"
                                           class="btn btn-outline-danger">&#10084;&#65039;</a>
                                    {% else %}
                                        <a href="{% url 'ManageProduct:add_to_favorite' product.pk %}"
                                           class="btn btn-outline-danger">🤍</a>
                                    {% endif %}

                                {% endif %}
                                {% if request.user.storeadminprofile and product.id in request.user.storeadminprofile.get_store_products_IDs %}
                                    <form action="{% url 'ManageProduct:delete_product' product.pk %}" method="post">
                                        {% csrf_token %}
                                        {% if product.store_set.first.id %}
                                            <a href="{% url 'ManageStore:view_store' product.store_set.first.id %}"><img
                                                    src="{{ product.store_set.first.image.url }}" alt="" height="40"
                                                    width="40"
                                                    style="position: marker; bottom: 10px; right: 10px;"></a>
                                        {% endif %}
                                        <button type="submit" class="btn btn-danger ">delete</button>
                                        <a href="{% url 'ManageProduct:update_product' product.pk %}"
                                           class="btn btn-warning ">Edit</a>
                                        <a href="{% url 'ManageProduct:product_view' product.pk %}"
                                           class="btn btn-success ">View</a>
                                    </form>
                                {% endif %}
                            </div>
                            <div>
                                <div class="card-footer">
                                    <div class="progress">
                                        <div class="progress-bar bg-success" role="progressbar"
                                             style="width: {{ product.average_review }}%"
                                             aria-valuenow="5"
                                             aria-valuemin="0" aria-valuemax="5">
                                            review {{ product.average_review }} %
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock product_card %}

ManageProduct/templates/product_confirm_delete.html
{% extends "base.html" %}
{% load bootstrap5 %}

{% block content %}
<h1>Product Delete</h1>
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>
{% endblock content %}

ManageProduct/templates/product_home.html
{% extends 'base.html' %}
{% block content %}
        <title>View Product</title>

    {% block  product_home %}
        <div class="container">
            <div class="row">
                {% block product_card %}
                    {% include 'product_card.html' with product=product %}
                {% endblock product_card %}

            </div>

            <div class="row ">
                <div class="col-6 ">

                    {% block PostNewReview %}
                        {% include 'PostNewReview.html' with form=form TO='ManageReview:add-product-review' id=product.id %}
                    {% endblock PostNewReview %}

                    {% for review in product.ProductReview.all %}
                        {% block review_card %}
                            {% include 'review_card.html' with review=review %}
                        {% endblock review_card %}
                    {% endfor %}

                </div>
            </div>

        </div>
    {% endblock product_home %}
{% endblock content %}

ManageProduct/templates/product_in_squre_card.html
<div class="col" >
    <div class="card" >
        <img class="img-fluid" src="{{ product.image.url }}" style="min-height: 150px;min-width:235px;max-height: 150px;max-width:235px ">
        <div class="card-body">
            <div class="card-title "><a
                    href="{% url 'ManageProduct:product_view' product.pk %}"><b>{{ product }}</b></a></div>

                <br><b>price </b> <small>{{ product.price }}$</small>
                <br><b>Type</b> <small>{{ product.type }}</small>
                <br><b>Discount</b><small>discount {{ product.discount }}%</small>
{#                <br><b>Description</b> <small> {{ product.description|slice:'10' }}...</small>#}

        </div>
        <div class="col align-self-end">
            {% if request.user.customerprofile %}
                {% if product.store_set.first.id %}
                    <a href="{% url 'ManageStore:view_store' product.store_set.first.id %}"><img
                            src="{{ product.store_set.first.image.url }}" alt="" height="40"
                            width="40"
                            style="position: marker; bottom: 10px; right: 10px;"></a>
                {% endif %}
                {% if product.id in  request.user.customerprofile.cart.get_product_ids %}
                    <a class="btn btn-danger" href="{% url 'ShoppingCart:edit_product_quantity_cart' product.id 0 %}">remove </a>
                {% else %}
                    <a class="btn btn-success" href="{% url 'ShoppingCart:add_product_to_cart' product.id 1 %}"> add</a>
                {% endif %}
                {% if product.id in  request.user.customerprofile.get_Customer_Favorite_IDs %}
                    <a href="{% url 'ManageProduct:remove_to_favorite' product.pk %}" class="btn btn-outline-danger">&#10084;&#65039;</a>
                {% else %}
                    <a href="{% url 'ManageProduct:add_to_favorite' product.pk %}" class="btn btn-outline-danger">🤍</a>
                {% endif %}
            {% endif %}
            {% if request.user.storeadminprofile and product.id in request.user.storeadminprofile.get_store_products_IDs %}
                <form action="{% url 'ManageProduct:delete_product' product.pk %}" method="post">
                    {% csrf_token %}
                    {% if product.store_set.first.id %}
                        <a href="{% url 'ManageStore:view_store' product.store_set.first.id %}"><img
                                src="{{ product.store_set.first.image.url }}" alt="" height="40" width="40"
                                style="position: marker; bottom: 10px; right: 10px;"></a>
                    {% endif %}
                    <button type="submit" class="btn btn-danger ">delete</button>
                    <a href="{% url 'ManageProduct:update_product' product.pk %}" class="btn btn-warning ">Edit</a>
                    <a href="{% url 'ManageProduct:product_view' product.pk %}" class="btn btn-success ">View</a>
                </form>
            {% endif %}
        </div>
        <div class="card-footer">
            <div class="progress">
                <div class="progress-bar bg-success" role="progressbar"
                     style="width: {{ product.average_review }}%"
                     aria-valuenow="5"
                     aria-valuemin="0" aria-valuemax="5">
                    review {{ product.average_review }} %
                </div>
            </div>
        </div>


    </div>
</div>

ManageProduct/templates/products_table.html
{% block product_table %}
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Type</th>
            <th scope="col">Number Of Copy</th>
            <th scope="col">Par Code</th>
            <th scope="col">Discount</th>
            <th scope="col">Options</th>
        </tr>
        </thead>
        <tbody>

        {% for product in products %}
            <tr>
                <td>
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="{{ product.id }}">
                        <label class="custom-control-label" for="{{ product.id }}"></label>
                    </div>
                </td>
                <th scope="row">{{ product.id }}</th>
                <td>{{ product.name }}</td>
                <td>{{ product.price }}</td>
                <td>{{ product.type }}</td>
                <td>{{ product.number_Of_Copy }}</td>
                <td>{{ product.par_Code }}</td>
                <td>{{ product.discount }}</td>

                <td>

                    <form action="{% url 'ManageProduct:delete_product' product.pk %}" method="post">
                        {% csrf_token %}
                        <button type="submit"
                                class="btn btn-danger ">delete
                        </button>
                        <a href="{% url 'ManageProduct:update_product' product.pk %}" class="btn btn-warning ">Edit</a>
                        <a href="{% url 'ManageProduct:product_view' product.pk %}" class="btn btn-success ">View</a>
                    </form>

                </td>
            </tr>


        {% empty %}
            <h1 align="center" style="color: red"><b> THE ARE NO PRODUCT </b></h1>

        {% endfor %}
        <hr>
        <div align="center">
        <a href="{% url 'ManageProduct:product_create' %}" class="btn btn-success ">ADD NEW PRODUCT </a>
        </div></tbody>

    </table>

{% endblock product_table %}