Dashboard/urls.py
from django.urls import path

from Dashboard import views

app_name = 'Dashboard'
urlpatterns = [
    path('', views.Home, name='Home'),
    path('section/<str:sec>', views.section, name='section'),
    path('filter', views.productsfilter, name='filter'),
    path('search', views.search, name='search'),
    path('Maptest', views.Maptest,name='Maptest')
]

ManageOffer/urls.py
from django.urls import path
from ManageOffer import views

app_name = 'ManageOffer'
urlpatterns = [
    path('view_all_offers/', views.view_all_offers, name='view_all_offers'),
    # path('view_store_offers/', views.view_store_offers, name='view_store_offers'),
    path('view_offer/<offer_id>', views.view_offer, name='view_offer'),
    path('create_offer/', views.create_offer, name='create_offer'),
    path('edit_offer/<offer_id>', views.edit_offer, name='edit_offer'),
    path('delete_offer/<offer_id>', views.delete_offer, name='delete_offer'),

]

ManageProduct/urls.py
from django.urls import path

from . import views
from .views import ProductAdmin ,ProductsCustomer

app_name = 'ManageProduct'
urlpatterns = [

    # path('ProductList/', ProductAdmin.view_all_products, name='view_all_products'),
    path('ProductCreate/', ProductAdmin.product_create, name='product_create'),
    path('ProductView/<int:pk>', ProductAdmin.product_view, name='product_view'),
    path('ProductUpdate/<int:pk>', ProductAdmin.update_product, name='update_product'),
    path('ProductDelete/<int:pk>', ProductAdmin.delete_product, name='delete_product'),
    # path('profilter/', views.profilter, name='profilter'),
    path('add_to_favorite/<int:id>', ProductsCustomer.add_to_favorite, name='add_to_favorite'),
    path('remove_to_favorite/<int:id>', ProductsCustomer.remove_to_favorite, name='remove_to_favorite'),

]

ManageStore/urls.py
from django.urls import path

from ManageStore import views

app_name = 'ManageStore'
urlpatterns = [

    path('Store/Detail/<int:store_id>', views.view_store, name='view_store'),
    path('Store/Detail/<int:store_id>/<str:section>', views.products_in_section, name='view_store_section'),
    path('Store/Create', views.create_store, name='create_store'),
    path('Edit/Store/Detail', views.edit_store, name='edit_store'),
    path('add/ad_img/', views.add_ADs, name='add_ADs'),
    path('delete/ad_img/<int:ad_id>', views.delete_ADs, name='delete_ADs'),


]

Project/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Shopping_Cart/', include('ShoppingCart.urls', namespace='ShoppingCart')),
    path('', include('Dashboard.urls', namespace='Dashboard')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('ManageProduct/', include('ManageProduct.urls', namespace='ManageProduct')),
    path('ManageStore/', include('ManageStore.urls', namespace='ManageStore')),
    path('ManageOffer/', include('ManageOffer.urls', namespace='ManageOffer')),
    path('ManageReview/', include('ManageReview.urls', namespace='ManageReview')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'Dashboard.views.error_404'

ShoppingCart/urls.py
from django.urls import path

from ShoppingCart import ShoppingCartView as view

app_name = "ShoppingCart"

urlpatterns = [

    path('viwe', view.view_shopping_cart, name='view_shopping_cart'),
    path('add/product/<int:product_id>/quantity/<int:quantity>', view.add_product_to_cart, name='add_product_to_cart'),
    path('edit/product/<int:product_id>/quantity/<int:quantity>', view.edit_product_quantity_cart,
         name='edit_product_quantity_cart'),
    path('add/product/<int:product_id>/quantity/<int:quantity>', view.add_offer_to_cart, name='add_offer_to_cart'),
    path('edit/product/<int:CartOffer_id>/quantity/<int:quantity>', view.edit_offer_quantity_cart,
         name='edit_offer_quantity_cart'),

    path('test/', view.mainUseCase, name='mainUseCase')

]

ManageOffer/models.py
from datetime import datetime

from django.core.validators import MinValueValidator
from django.db import models
from django.template.defaultfilters import slugify

from ManageProduct.models import Product
from ManageReview.models import Review


class Offer(models.Model):
    products = models.ManyToManyField(Product, blank=True)
    expiratiDate = models.DateTimeField(default=datetime.now)
    state = models.BooleanField(default=False)
    name = models.CharField(max_length=50, blank=True)
    number_OF_Copy = models.PositiveIntegerField(default=0)
    price = models.FloatField(validators=[MinValueValidator(0.0)], default=0.0)
    image = models.ImageField(upload_to='Offers', default='package default.jpg')
    slug = models.SlugField(unique=True)
    review = models.ManyToManyField(Review, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Offer, self).save(*args, **kwargs)

    def __str__(self):
        # temp =datetime.date()
        # self.state = temp <= self.expiratiDate
        return self.name

    def average_review(self):
        revs = self.review.all()

        if revs:
            total = 0
            for x in revs:
                total += x.rating
            return (total / len(revs)) * 20
        else:
            return 0

ManageOffer/forms.py
from ManageOffer.models import Offer
from django import forms


class OfferForm(forms.ModelForm):
    class Meta:
        model = Offer
        fields = '__all__'
        exclude = ['StoreId','slug']

ManageOffer/views.py
from django.shortcuts import get_object_or_404, redirect, render
from ManageOffer.forms import OfferForm
from ManageOffer.models import Offer
from ManageStore.models import Store
from accounts.models import StoreAdminProfile
from django.core.paginator import Paginator


def create_offer(request):
    user = get_object_or_404(StoreAdminProfile, user=request.user)
    store = get_object_or_404(Store, id=user.store.pk)
    form = OfferForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        store.StoreOffers.add(form.instance)
        store.save()
        return redirect('accounts:StoreAdminProfileView')
    else:
        form = OfferForm()
    context = {'form': form}

    return render(request, 'create_offer.html', context)


def edit_offer(request, offer_id):
    user = get_object_or_404(StoreAdminProfile, user=request.user)
    store = get_object_or_404(Store, id=user.store.pk)
    offer = get_object_or_404(Offer, id=offer_id)
    if request.method=="POST":
        form = OfferForm(request.POST or None, request.FILES or None, instance=offer)
        if form.is_valid():
            form.save()
            store.StoreOffers.add(form.instance)
            store.save()
            return redirect('accounts:StoreAdminProfileView')
    else:
        form = OfferForm(instance=offer)
    context = {'form': form}
    return render(request, 'Edit_Offer.html', context)


def delete_offer(request, offer_id):
    offer = get_object_or_404(Offer, pk=offer_id)
    storeadmin = get_object_or_404(StoreAdminProfile, user=request.user)
    if storeadmin.store.StoreOffers.get(id=offer_id)and request.POST:
        offer.delete()
        return redirect('accounts:StoreAdminProfileView')


def view_offer(request ,offer_id ):
    offer= get_object_or_404(Offer,pk=offer_id )
    return render( request , 'offer_home.html' , {'offer': offer} )


def view_all_offers(request):
    offer=Offer.objects.all()
    paginator = Paginator((offer), 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render( request , 'OfferTemplate.html' , {'offers': offer ,'page_obj': page_obj,} )

ManageOffer/templates/AD_s.html
{% block AD_Slieds %}

    <div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
        <div class="carousel-inner">

                <div class="carousel-item active">
                    <img src="{{ ads.first.ad_imags.url }}" class="d-block" alt="..."
                         style="min-height:300px;min-width:100%;max-height: 300px;max-width:100% ">
                </div>
                {% for ad in ads %}
                    <div class="carousel-item">
                        <img src="{{ ad.ad_imags.url }}" class="d-block" alt="..."
                             style="min-height:300px;min-width:100%;max-height: 300px;max-width:100% ">
                    </div>
                    {% empty %}
                    <div class="carousel-item active">
                    <img src="http://placehold.it/900x350" class="d-block" alt="..."
                         style="min-height:300px;min-width:100%;max-height: 300px;max-width:100% ">
                </div>
                {% endfor %}
        </div>

        <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </a>
    </div>

{% endblock %}

ManageOffer/templates/Edit_Offer.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
    <title>Edit Offer</title>


    {#{% block AddOffer %}#}

    <legend>Edit Offer</legend>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Save" class="btn btn-success">
    </form>
    <hr>
    <a href="{% url 'ManageProduct:product_create' %}" class="btn btn-success" style="margin-right: 0px"> Create new Product </a>

    {#{% endblock AddOffer %} #}
{% endblock content %}

ManageOffer/templates/OfferTemplate.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
    <title>View All offer</title>
    <body>
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">

                {% for offer in  page_obj %}
                    <div class="col-md-4">
                        <div class="card mb-4 box-shadow">
                            <img class="card-img-top" src="{{ offer.image.url }}" alt="Thumbnail [100%x225]"
                                 style="height: 225px; width: 100%; display: block;"
                                 src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22348%22%20height%3D%22225%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20348%20225%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_17740bf2956%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A17pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_17740bf2956%22%3E%3Crect%20width%3D%22348%22%20height%3D%22225%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22117.5%22%20y%3D%22120.45%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E"
                                 data-holder-rendered="true">
                            <div class="card-body">
                                <p class="card-text">{{ offer }}</p>
                                <p>Price :{{ offer.price }}</p>
                                <p>Available to :{{ offer.expiratiDate }} </p>
                                <p>Number OF Copy :{{ offer.number_OF_Copy }}</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-sm btn-outline-secondary"><a
                                                href="{% url 'ManageOffer:view_offer' offer.pk %}">View</a></button>
                                    </div>
                                    {% comment %}
                    <small class="text-muted">State :{{ offer.state }}</small>
{% endcomment %}
                                </div>
                            </div>
                        </div>
                    </div>
                {% empty %}
                    <H1>no offer </H1>
                {% endfor %}
                {% if page_obj %}
                    <div class="row" style="padding-top: 50px">
                        <div class="col-4"> &emsp;</div>
                        <div class="col-6">
                            <nav aria-label="...">
                                <ul class="pagination">
                                    <li class="page-item disabled">
                                        {% if page_obj.has_previous %}
                                            <li class="page-item"><a class="page-link" href="?page=1">&laquo;
                                                first</a>
                                            </li>


                                            <span class="page-link"
                                                  href="?page={{ page_obj.previous_page_number }}">Previous</span>

                                            <li class="page-item"><a class="page-link"
                                                                     href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
                                            </li>
                                            </li>
                                        {% endif %}
                                    <li class="page-item active" aria-current="page">
                                        <span class="page-link"> {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
                                    </li>
                                    {% if page_obj.has_next %}
                                        <li class="page-item"><a class="page-link"
                                                                 href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                                        </li>

                                        <li class="page-item">
                                            <a class="page-link"
                                               href="?page={{ page_obj.next_page_number }}">Next</a>
                                        </li>
                                        <li class="">
                                            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last
                                                &raquo;</a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </nav>

                        </div>

                    </div>
                {% else %}
                    <a href="{% url 'Dashboard:Home' %}" class="btn btn-success"> back to Home </a>
                {% endif %}

            </div>
        </div>
    </div>
    </body>
{% endblock %}

ManageOffer/templates/create_offer.html
{% extends 'base.html' %}
{% load bootstrap5 %}
 {% block content %}
    <title>Create Offer</title>


{#{% block AddOffer %}#}

    <legend>Add New Offer </legend>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <br><input type="submit" value="Add">
    </form>
{#{% endblock AddOffer %} #}
 {% endblock content %}

ManageOffer/templates/offer_card.html
    {% block offer_card %}
        <div class="container">
            <div class="row">
                <div class="card mb-1">
                    <div class="row md-1">
                        <div class="col-md-3">
                             <img class="img-fluid" src="{{ offer.image.url }}"
                                 style="height: 300px;width: 300px">
                        </div>
                        <div class="col-md-9">

                            <div class="col-md-8">
                                <div class="card-title "><a href="#" style="text-decoration: none "><b>{{ offer }}</b></a>
                                </div>
                                <div class="card-body">
                                    <div class="container">
                                        <div class="row">
                                            <div class="col-sm">
                                                <b>Offer Products: </b>
                                                {% for product in offer.products.all %}
                                                    <small><a
                                                            href="{% url 'ManageProduct:product_view' product.pk %}">{{ product }}</a></small>
                                                    &nbsp;|
                                                    {% empty %}
                                                    <h5 style="color: red">The are no Products Offer </h5>
                                                {% endfor %}
                                                <hr>
                                                <b>Expire Date: {{ offer.expiratiDate }} </b>{{ offer.State }}<br>
                                                <b>Available: </b>{{ offer.state }}<br>
                                                <b>Number Of Copy: </b>{{ offer.number_OF_Copy }} <br>
                                                <b>Package_Price: </b>{{ offer.price }} <br>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col align-self-end">
                                {% if request.user.customerprofile %}
                                    {% if product.store_set.first.id %}
                                        <a href="{% url 'ManageStore:view_store' product.store_set.first.id %}"><img
                                                src="{{ product.store_set.first.image.url }}" alt="" height="40"
                                                width="40"
                                                style="position: marker; bottom: 10px; right: 10px;"></a>
                                    {% endif %}
                                    {% if product.id in  request.user.customerprofile.cart.get_offer_ids %}
                                        <a class="btn btn-danger"
                                           href="{% url 'ShoppingCart:edit_offer_quantity_cart' offer.id 0 %}">remove </a>
                                    {% else %}
                                        <a class="btn btn-success"
                                           href="{% url 'ShoppingCart:add_offer_to_cart' offer.id 1 %}"> add</a>
                                    {% endif %}
                                {% endif %}
                                {% if request.user.storeadminprofile and offer.id in request.user.storeadminprofile.get_store_offer_IDs %}
                                    <form action="{% url 'ManageOffer:delete_offer' offer.pk %}" method="post">
                                        {% csrf_token %}
                                        {% if offer.store_set.first.id %}
                                            <a href="{% url 'ManageStore:view_store' offer.store_set.first.id %}"><img
                                                    src="{{ product.store_set.first.image.url }}" alt="" height="40"
                                                    width="40"
                                                    style="position: marker; bottom: 10px; right: 10px;"></a>
                                        {% endif %}
                                        <button type="submit" class="btn btn-danger ">delete</button>
                                        <a href="{% url 'ManageOffer:edit_offer' offer.pk %}"
                                           class="btn btn-warning ">Edit</a>
                                        <a href="{% url 'ManageOffer:view_offer' offer.pk %}"
                                           class="btn btn-success ">View</a>
                                    </form>
                                {% endif %}
                            </div>
                            <div>
                                <div class="card-footer">
                                    <div class="progress">
                                        <div class="progress-bar bg-success" role="progressbar"
                                             style="width: {{ product.average_review }}%"
                                             aria-valuenow="5"
                                             aria-valuemin="0" aria-valuemax="5">
                                            review {{ offer.average_review }} %
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

            </div>
        </div>

    {% endblock offer_card %}

ManageOffer/templates/offer_home.html
{% extends 'base.html' %}

{% block content %}
    <title>View Offer</title>

{% ifnotequal offer None %}
{{ offer.price }}
{% endifnotequal %}


    <section>
        {% block offer_card %}
            {% include 'offer_card.html' with offer=offer %}
        {% endblock %}
    </section>
    <section>

        {% block PostNewReview %}
            {% include 'PostNewReview.html' with form=form TO='ManageReview:add_offer_review' id=offer.pk  %}
        {% endblock PostNewReview %}

    </section>
    <section>
        {% for review in offer.review.all %}
            {% block review_card %}
                {% include 'review_card.html' with review=review %}
            {% endblock review_card %}
            {% empty %}
            NON
        {% endfor %}
    </section>





{% endblock content %}

ManageOffer/templates/offer_squre_card.html
    <div class="card">
        <a href="{% url 'ManageOffer:view_offer' offer.id %}">
            <img src="{{ offer.image.url }}" class="img-fluid" alt="" style="min-height: 150px;min-width:279px;max-height: 150px;max-width:280px">
        </a>
        <div class="card-body">
            <div class="card-title "><b>{{ offer.name }}</b> </div>
                {% for product in offer.products.all %}
                    <small><a href="{% url 'ManageProduct:product_view' product.pk %}">{{ product }}</a>&nbsp|</small>

                {% empty %}
                    <h5 style="color: red">The are no Products Offer </h5>
                {% endfor %}

            <br><b>price </b> <small>{{ offer.price }}$</small>
            <br><b>Expirati Date</b> <small>{{ offer.expiratiDate }}</small>
            <br><b>#Copy</b><small> {{ offer.number_OF_Copy }}</small>


            <div class="align-self-end">
                {% if request.user.customerprofile %}
                    {% if product.store_set.first.id %}
                        <a href="{% url 'ManageStore:view_store' product.store_set.first.id %}"><img
                                src="{{ product.store_set.first.image.url }}" alt="" height="40"
                                width="40"
                                style="position: marker; bottom: 10px; right: 10px;">
                        </a>
                    {% endif %}
                    {% if product.id in  request.user.customerprofile.cart.get_offer_ids %}
                        <a class="btn btn-danger"
                           href="{% url 'ShoppingCart:edit_offer_quantity_cart' offer.id 0 %}">remove </a>
                    {% else %}
                        <a class="btn btn-success"
                           href="{% url 'ShoppingCart:add_offer_to_cart' offer.id 1 %}"> add</a>
                    {% endif %}
                {% endif %}
                {% if request.user.storeadminprofile and offer.id in request.user.storeadminprofile.get_store_offer_IDs %}

                    {% if offer.store_set.first.id %}
                        <a href="{% url 'ManageStore:view_store' offer.store_set.first.id %}">
                            <img
                                    src="{{ product.store_set.first.image.url }}" alt="" height="40"
                                    width="40"
                                    style="position: marker; bottom: 10px; right: 10px;">
                        </a>
                    {% endif %}
                    <a href="{% url 'ManageOffer:delete_offer' offer.pk %}"
                       class="btn btn-danger ">Delet</a>
                    <a href="{% url 'ManageOffer:edit_offer' offer.pk %}"
                       class="btn btn-warning ">Edit</a>

                {% endif %}
                <a href="{% url 'ManageOffer:view_offer' offer.pk %}"
                   class="btn btn-success ">View</a>

            </div>
        </div>

        <div>

            <div class="card-footer">
                <div class="progress">
                    <div class="progress-bar bg-success" role="progressbar"
                         style="width: {{ offer.average_review }}%"
                         aria-valuenow="5"
                         aria-valuemin="0" aria-valuemax="5">
                        review {{ offer.average_review }} %
                    </div>
                </div>
            </div>


        </div>
    </div>

ManageOffer/templates/offers_table.html
{% block offer_table %}
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Products</th>
            <th scope="col">Package Price</th>
            <th scope="col">Expiration Date</th>
            <th scope="col">State</th>
            <th scope="col">Number Of Copy</th>
            <th scope="col">Options</th>
        </tr>
        </thead>

        <tbody>

        {% for offer in offers %}
            <tr>
                <td>
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="{{ offer.id }}">
                        <label class="custom-control-label" for="{{ offer.id }}"></label>
                    </div>
                </td>
                <th scope="row">{{ offer.id }}</th>
                <td>{{ offer.name }}</td>

                <td>
                    {% for product in offer.products.all %}
                        {{ product.name }}<br>
                    {% endfor %}
                </td>

                <td>{{ offer.price }}</td>
                <td>{{ offer.expiratiDate }}</td>
                <td>{{ offer.state }}</td>
                <td>{{ offer.number_OF_Copy }}</td>
                <td>

                    <form action="{% url 'ManageOffer:delete_offer' offer.pk %}" method="post">
                        {% csrf_token %}
                        <button type="submit"
                                class="btn btn-danger ">delete
                        </button>
                        <a href="{% url 'ManageOffer:edit_offer' offer.pk %}" class="btn btn-warning ">Edit</a>
                        <a href="{% url 'ManageOffer:view_offer' offer.pk %}" class="btn btn-success ">View</a>
                    </form>

                </td>
            </tr>
        {% empty %}
        <h1 align="center" style="color: red"><b> THE ARE NO OFFER </b></h1>

        {% endfor %}

        </tbody>
      <div align="center">
                 <a  href="{% url 'ManageOffer:create_offer' %}" class="btn btn-success ">Create New Offer </a>
    </div>
    </table>

{% endblock offer_table %}