Dashboard/urls.py
from django.urls import path

from Dashboard import views

app_name = 'Dashboard'
urlpatterns = [
    path('', views.Home, name='Home'),
    path('section/<str:sec>', views.section, name='section'),
    path('filter', views.productsfilter, name='filter'),
    path('search', views.search, name='search'),
    path('Maptest', views.Maptest,name='Maptest')
]

ManageOffer/urls.py
from django.urls import path
from ManageOffer import views

app_name = 'ManageOffer'
urlpatterns = [
    path('view_all_offers/', views.view_all_offers, name='view_all_offers'),
    # path('view_store_offers/', views.view_store_offers, name='view_store_offers'),
    path('view_offer/<offer_id>', views.view_offer, name='view_offer'),
    path('create_offer/', views.create_offer, name='create_offer'),
    path('edit_offer/<offer_id>', views.edit_offer, name='edit_offer'),
    path('delete_offer/<offer_id>', views.delete_offer, name='delete_offer'),

]

ManageStore/urls.py
from django.urls import path

from ManageStore import views

app_name = 'ManageStore'
urlpatterns = [

    path('Store/Detail/<int:store_id>', views.view_store, name='view_store'),
    path('Store/Detail/<int:store_id>/<str:section>', views.products_in_section, name='view_store_section'),
    path('Store/Create', views.create_store, name='create_store'),
    path('Edit/Store/Detail', views.edit_store, name='edit_store'),
    path('add/ad_img/', views.add_ADs, name='add_ADs'),
    path('delete/ad_img/<int:ad_id>', views.delete_ADs, name='delete_ADs'),


]

Project/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Shopping_Cart/', include('ShoppingCart.urls', namespace='ShoppingCart')),
    path('', include('Dashboard.urls', namespace='Dashboard')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('ManageProduct/', include('ManageProduct.urls', namespace='ManageProduct')),
    path('ManageStore/', include('ManageStore.urls', namespace='ManageStore')),
    path('ManageOffer/', include('ManageOffer.urls', namespace='ManageOffer')),
    path('ManageReview/', include('ManageReview.urls', namespace='ManageReview')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'Dashboard.views.error_404'

ShoppingCart/urls.py
from django.urls import path

from ShoppingCart import ShoppingCartView as view

app_name = "ShoppingCart"

urlpatterns = [

    path('viwe', view.view_shopping_cart, name='view_shopping_cart'),
    path('add/product/<int:product_id>/quantity/<int:quantity>', view.add_product_to_cart, name='add_product_to_cart'),
    path('edit/product/<int:product_id>/quantity/<int:quantity>', view.edit_product_quantity_cart,
         name='edit_product_quantity_cart'),
    path('add/product/<int:product_id>/quantity/<int:quantity>', view.add_offer_to_cart, name='add_offer_to_cart'),
    path('edit/product/<int:CartOffer_id>/quantity/<int:quantity>', view.edit_offer_quantity_cart,
         name='edit_offer_quantity_cart'),

    path('test/', view.mainUseCase, name='mainUseCase')

]

accounts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path

from accounts import views
from accounts.views import CustomerViews, StoreAdminViews

app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logged_out.html'), name='logout'),

    path('password_change/',
         auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html'),
         name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),

    path('SignUp/', views.SignUpView.as_view(), name='signup'),



    path('Customer/Profile', CustomerViews.Customer_Profile_View, name='CustomerProfileView'),
    path('Customer/Edit/Profile', CustomerViews.Customer_Edit_Profile_View,
         name='Customer_Edit_Profile_View'),
    # path('Customer/FavoriteList', CustomerViews.get_FavoriteList,
    #      name='FavoriteList'),







    path('StoreAdmin/Profile', StoreAdminViews.StoreAdmin_Profile_View,
         name='StoreAdminProfileView'),
    path('StoreAdmin/Edit/Profile', StoreAdminViews.StoreAdmin_Edit_Profile_View,
         name='StoreAdminEditProfileView'),





]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
'''



    path('shopping_list', views.shoppinglist, name='Shopping list'),
    path('favorite', views.favorite, name='Favorite'),
    path('Offer', views.Offer, name='Offer'),
    path('reward', views.Reward, name='Reward'),
    path('ProvideReview', views.ProvideReview, name='Provide Review'),
    # Store Admin view
    path('ManageOffer', views.ManageOffer, name='Manage Offer'),
    path('ManagerProduct', views.ManagerProduct, name='Manager Product'),
#System Admin view
    path('ManageOffer', views.ManageOffer, name='Manage Advertisement'),
    path('Manage Reward', views.ManageReward, name='Manage Reward'),
    path('Manage Accounts', views.ManageAccounts, name='Manage Accounts'),

'''

accounts/models.py
from datetime import datetime
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify
from django_countries.fields import CountryField
from ManageStore.models import Store
from ShoppingCart.models import ShoppingCart


class StoreAdminProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, null=True)
    image = models.ImageField(upload_to='StoreAdminProfileImages',
                              default='Customer default.png')
    address = models.CharField(max_length=100, blank=True, null=True)
    join_at = models.DateTimeField(default=datetime.now)
    country = CountryField(default='Jordan')
    store = models.OneToOneField(Store, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Store Admin Profile'

    def __str__(self):
        return str(self.user)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.user)
        if not self.store:
            self.store = Store.objects.create()
        super(StoreAdminProfile, self).save(*args, **kwargs)

    @property
    def get_slug(self):
        return self.slug

    def get_store_products_IDs(self):
        IDs = []
        for product in self.store.products.all():
            IDs.append(product.id)
        return IDs

    def get_store_offer_IDs(self):
        IDs = []
        for offer in self.store.StoreOffers.all():
            IDs.append(offer.id)
        return IDs

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from accounts.CustomerProfilemodel import CustomerProfile
from accounts.models import StoreAdminProfile


class SignupForm(UserCreationForm, forms.ModelForm):
    user_type = (
        ('Customer', 'Customer'),
        ('StoreAdmin', 'StoreAdmin'),
    )

    typee = forms.ChoiceField(choices=user_type, label="Account Type is ? ")

    class Meta(UserCreationForm.Meta):
        model = User
        fields = [
            'username',
            'password1',
            'password2',
            'first_name',
            'last_name',
            'email',
            'typee',
        ]


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', ]


class StoreAdminEditForm(forms.ModelForm):
    class Meta:
        model = StoreAdminProfile
        fields = ['image', 'country', 'address']


class CustomerForm(forms.ModelForm):
    class Meta:
        model = CustomerProfile
        fields = ['address', 'image', 'country', ]

accounts/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import CreateView

from ManageStore.forms import ADForm
from accounts.forms import CustomerForm, StoreAdminEditForm, UserEditForm
from .CustomerProfilemodel import CustomerProfile
from .forms import SignupForm
from .models import StoreAdminProfile


class SignUpView(CreateView):
    template_name = 'signup.html'
    model = User
    form_class = SignupForm

    def form_valid(self, form):
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            if form.cleaned_data['typee'] == 'Customer':
                user = authenticate(username=username, password=password)
                Profile = CustomerProfile.objects.create(user=user)
                login(self.request, user)
                return redirect('accounts:CustomerProfileView')

            elif form.cleaned_data['typee'] == 'StoreAdmin':
                user = authenticate(username=username, password=password)
                Profile = StoreAdminProfile.objects.create(user=user)
                login(self.request, user)
                return redirect('accounts:StoreAdminProfileView')

            else:
                raise Http404

    def get(self, request, *args, **kwargs):
        form = SignupForm()

        return render(request, self.template_name, {'form': form})


class CustomerViews():

    def Customer_Profile_View(request):
        user = get_object_or_404(CustomerProfile, user=request.user)
        favorites = user.favorite.all()

        return render(request, 'CustomerProfile.html', {'Profile': user, 'favorites': favorites})

    def Customer_Edit_Profile_View(request):
        user = get_object_or_404(CustomerProfile, user=request.user)
        if request.method == 'POST':
            user_form = UserEditForm(request.POST or None, request.FILES or None, instance=user)
            form = CustomerForm(request.POST or None, request.FILES or None, instance=user)
            if form.is_valid():
                edit = form.save(commit=False)
                edit.save()
            return redirect('accounts:CustomerProfileView')
        else:
            user_form = UserEditForm(instance=user)
            form = CustomerForm(instance=user)
        return render(request, 'CustomerEditInfo.html', {'form': form, 'user_form': user_form})



class StoreAdminViews():
    def StoreAdmin_Profile_View(request):
        user = get_object_or_404(StoreAdminProfile, user=request.user)
        form = ADForm()
        return render(request, 'StoreAdminProfile.html', {'Profile': user , 'form':form})

    def StoreAdmin_Edit_Profile_View(request):
        user = get_object_or_404(StoreAdminProfile, user=request.user)

        if request.method == 'POST':
            user_form = UserEditForm(request.POST or None, request.FILES or None, instance=request.user)
            form = StoreAdminEditForm(request.POST or None, request.FILES or None, instance=user)
            if form.is_valid() and user_form.is_valid():
                user_form.save()
                form.save()
            return redirect('accounts:StoreAdminProfileView')
        else:
            user_form = UserEditForm(instance=request.user)
            form = StoreAdminEditForm(instance=user)
        return render(request, 'StoreAdminEditInfo.html', {'form': form, 'user_form': user_form})

accounts/templates/CustomerEditInfo.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% block content %}
        <title>Edit Profile</title>

    <div class="container" style="padding-top: 56px">
        <form action="" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% bootstrap_form user_form %}
            <br>
            <div align="center">
                <button type="submit" class="btn btn-success zoom_in">save</button>
            </div>
        </form>
    </div>
{% endblock content %}

accounts/templates/CustomerProfile.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% load static %}

{% block content %}
        <title>My Profile</title>

    <div class="container-fluid" style="padding-top: 2%">
        <div class="row">
            <div class="col-3">
                {% block profile %}
                    {% include 'Customer_Card_Info.html' with profile=Profile %}
                {% endblock profile %}
            </div>
            <div class="col-9" align="center">

                {% include 'Customer_FavoriteList.html' with favorites=favorites %}

            </div>
        </div>
    </div>
{% endblock content %}

accounts/templates/Customer_Card_Info.html
{% load static %} {% block profile %}

<div class="bd-example">
    <div class="card" style="width: 18rem">
    
        <img src= "{{ profile.image.url }}" class="img-fluid">

        <div class="card-body">
            <h5 class="card-title">{{ profile }}</h5>
            <p class="card-text"></p>
            <div class="list-group-item"><b>address :</b>{{ profile.address }}</div>
            <div class="list-group-item"><b>join_at :</b>{{ profile.join_at }}</div>
            <div class="list-group-item">
                <b>country :</b>{{ profile.country.name }}
            </div>
            <div class="list-group-item">
                <b> last login :</b>{{ profile.user.last_login }}
            </div>

            <a class="btn btn-primary zoom_in" href="{% url 'accounts:Customer_Edit_Profile_View' %}" role="button">Edit
                Profile</a>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/Customer_FavoriteList.html
{% block FavoriteList %}
    <div class="row">
        <div class="card-title">
            <h3>My Favorite</h3>
        </div>
        {% for item in  favorites %}
            <div class="col-3">
                {% include 'product_in_squre_card.html' with product=item %}
            </div>
        {% empty %}
            <h3 class="card-body" style="color: #ff001b">Favorite Empty</h3>
        {% endfor %}
    </div>
{% endblock FavoriteList %}

accounts/templates/Customer_nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="Dashboard:Home">Smart Shopper</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                <li class="nav-item">
                    <a href="{% url 'ShoppingCart:mainUseCase' %}" class="btn btn-success zoom_out"> Get Best
                        Choices</a>
                </li>
                <li class="nav-item">
                    &bull;
                </li>
                <li class="nav-item">
                    <a class="nav-link zoom_out " href="{% url 'Dashboard:Home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link zoom_out" href="{% url 'accounts:CustomerProfileView' %}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link zoom_out"
                       href="{% url 'ShoppingCart:view_shopping_cart' %}">MyCart {{ request.user.storeadminprofile.store }}</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link zoom_out " href="{% url 'Dashboard:Maptest' %}">Map Test</a>
                </li>
                </li>
                <li class="nav-item">
                    <a class="nav-link zoom_out " href="{% url 'ManageOffer:view_all_offers' %}">Offers</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link zoom_out" href="{% url 'accounts:logout' %}">logout</a>
                </li>
            </ul>
            <form class="d-flex" action="{% url 'Dashboard:search' %}" method="GET" value="{{ request.GET.q }}">
                <input class="form-control me-2 zoom_out" type="search" placeholder="Search" aria-label="Search"
                       name="q"
                       value="{{ request.GET.q }}">
                <button class="btn btn-outline-success zoom_out" type="submit">Search</button>
            </form>

        </div>
    </div>
</nav>

accounts/templates/StoreAdminCardInfo.html
{% block StoreAdminCardInfo %}
    <div class="col">
        <div class="card">
            <div class="card-img-top">
                {% if profile.image %}
                    <img class="img-fluid" src="{{ profile.image.url }}">
                {% else %}
                    <img src="http://placehold.it/400x400" class="card-img-top" alt="...">
                {% endif %}
            </div>
            <h5 class="card-title" align="center">
                <b>{{ profile.user }}</b>
            </h5>
            <div class="card-body">
                <h6><b> Address </b>{{ profile.address }} </h6>
                <h6><b> Join At </b> {{ profile.join_at }}</h6>
                <h6><b> Country </b>{{ profile.country.name }} </h6>
                <h6><b> Manager of Store </b> {{ profile.store }}</h6>
                <h6><b> Number Of Products </b> {{ profile.store.products.count }}</h6>
            </div>
            <div class="card-footer">
                <small class="text-muted">Last Login{{ request.user.last_login }}</small>
                <a class="btn btn-primary zoom_in"
                   href="{% url 'accounts:StoreAdminEditProfileView' %}">Edit
                    Profile</a>
            </div>
        </div>
    </div>
{% endblock StoreAdminCardInfo %}

accounts/templates/StoreAdminEditInfo.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% block content %}
        <title>Edit Profile</title>

    <div class="container" style="padding-top: 56px">
        <form action="" enctype="multipart/form-data" method="post">
            {% csrf_token %} {% bootstrap_form user_form %}
            {% bootstrap_form form %}
            <br>
            <hr>
            <div align="center">
                <input type="submit" value="Update" class="btn btn-success zoom_in" align="center">
            </div>
        </form>
    </div>
{% endblock %}

accounts/templates/StoreAdminProfile.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% load static %}
{% block content %}
        <title>Store Admin Profile</title>

    <div class="container-fluid" style="padding-top: 2%">
        <div class="row">

            <div class="col-lg-3 col-md-3 col-sm-3 ">
                {% block StoreAdminCardInfo %}
                    {% include 'StoreAdminCardInfo.html' with  profile=Profile %}
                {% endblock StoreAdminCardInfo %}
            </div>
            <div class="col-lg-9 col-md-9 col-sm-9">

                {% block Store_services %}
                    {% include 'Store_services.html' with store=Profile.store form=form %}
                {% endblock Store_services %}


            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/StoreAdmin_nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="Dashboard:Home">Smart Shopper</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active zoom_in" aria-current="page" href="{% url 'Dashboard:Home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active zoom_in" aria-current="page" href=" {% url 'accounts:StoreAdminProfileView' %}">Profile</a>

                </li>
                <li class="nav-item">
                </li>
                <li class="nav-item">
                    <a class="nav-link active zoom_in" aria-current="page"
                       href="{% url 'ManageStore:view_store' request.user.storeadminprofile.store.id %}">My Store (
                        {{ request.user.storeadminprofile.store }} )</a>
                </li>
                  <li class="nav-item">
                    <a class="nav-link zoom_out " href="{% url 'Dashboard:Maptest' %}">Map Test</a>
                </li>

                 </li>
                  <li class="nav-item">
                    <a class="nav-link zoom_out " href="{% url 'ManageOffer:view_all_offers' %}">Offers</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link zoom_in" href="{% url 'accounts:logout' %}">logout</a>
                </li>
            </ul>
            <form class="d-flex" action="{% url 'Dashboard:search' %}" method="GET" value="{{ request.GET.q }}">
                <input class="form-control me-2 zoom_in " type="search" placeholder="Search" aria-label="Search" name="q"
                       value="{{ request.GET.q }}">
                <button class="btn btn-outline-success zoom_in" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>


{% comment %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Dashboard:Home' %}">Home</a>
                </li>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-list-4"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbar-list-4">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <img src="https://s3.eu-central-1.amazonaws.com/bootstrapbaymisc/blog/24_days_bootstrap/fox.jpg"
                                     width="30" height="30" class="rounded-circle">
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">

                                <a class="dropdown-item"
                                   href="{% url 'accounts:StoreAdminProfileView' request.user.storeadminprofile %}">Profile
                                    Info </a>

                                <a class="dropdown-item"
                                   href="{% url 'accounts:StoreAdminEditProfileView' request.user.storeadminprofile.slug %}">Edit
                                    Profile</a>
                                <a class="dropdown-item" href="{% url 'Dashboard:Home' %}">Dashboard</a>
                                <a class="dropdown-item" href="{% url 'ManageOffer:Offerview' %}">MangeOffer</a>
                                <a class="dropdown-item" href="{% url 'ManageProduct:product_new' %}">AddProduct</a>
                                <a class="dropdown-item" href="{% url 'ManageStore:EditStoreDetail' request.user.storeadminprofile.store.id %}">EditStore</a>
                                #<a class="dropdown-item" href="{% url 'Man' %}">AddOffer</a>

                                <a class="dropdown-item" href="{% url 'accounts:logout' %}">Log Out</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </ul>
        </div>
    </div>
</nav>
{% endcomment %}

accounts/templates/signup.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% block content %}
    <title>Sign Up</title>


    <div class="row">
        <div class="col-md-2 col-sm-2 col-2"></div>
            <div class="col-md-8 col-sm-10 col-12">
            <h2>Sign up</h2>
            <form method="post" novalidate>
                {% csrf_token %}
                {#                <input type="hidden" name="next" value="{{ next }}">#}
                {% bootstrap_form form %}
                <button type="submit" class="btn btn-success zoom_in">Sign up</button>
            </form>
        </div>
    </div>



    {% comment %}  <h2>Sign up for a free account</h2>
    <p class="lead">Select below the type of account you want to create</p>
    <a href="{% url 'Customer_signup' %}" class="btn btn-student btn-lg" role="button">I'm a Customer</a>
    <a href="{% url 'StoreAdmin_signup' %}" class="btn btn-teacher btn-lg" role="button">I'm a StoreAdmin</a>{% endcomment %}
{% endblock %}

accounts/templates/xx.html
{% block xx %}


    {% block xx %}
        {% include 'xx.html' %}
    {% endblock xx %} </p>
    <head>
        <script type="text/javascript">
            function showLocation(position) {
                var latitude = position.coords.latitude;
                var longitude = position.coords.longitude;
                var latlongvalue = position.coords.latitude + ","
                    + position.coords.longitude;
                var img_url = "https://maps.googleapis.com/maps/api/staticmap?center="
                    + latlongvalue + "&amp;zoom=14&amp;size=400x300&amp;key=AIzaSyD78Ek7cEuUcGxqtFfgxC7jvENoHWkHP7I";
                document.getElementById("mapholder").innerHTML = "<img src='" + img_url + "'>";
            }

            function errorHandler(err) {
                if (err.code == 1) {
                    alert("Error: Access is denied!");
                } else if (err.code == 2) {
                    alert("Error: Position is unavailable!");
                }
            }

            function getLocation() {
                if (navigator.geolocation) {
                    // timeout at 60000 milliseconds (60 seconds)
                    var options = {timeout: 60000};
                    navigator.geolocation.getCurrentPosition
                    (showLocation, errorHandler, options);
                } else {
                    alert("Sorry, browser does not support geolocation!");
                }
            }
        </script>
    </head>
    <body>
    <div id="mapholder"></div>
    <form>
        <input type="button" onclick="getLocation();" value="Get Location"/>
    </form>
    </body>
{% endblock xx %}