ManageStore/urls.py
from django.urls import path

from ManageStore import views

app_name = 'ManageStore'
urlpatterns = [

    path('Store/Detail/<int:store_id>', views.view_store, name='view_store'),
    path('Store/Detail/<int:store_id>/<str:section>', views.products_in_section, name='view_store_section'),
    path('Store/Create', views.create_store, name='create_store'),
    path('Edit/Store/Detail', views.edit_store, name='edit_store'),
    path('add/ad_img/', views.add_ADs, name='add_ADs'),
    path('delete/ad_img/<int:ad_id>', views.delete_ADs, name='delete_ADs'),


]

Project/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Shopping_Cart/', include('ShoppingCart.urls', namespace='ShoppingCart')),
    path('', include('Dashboard.urls', namespace='Dashboard')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('ManageProduct/', include('ManageProduct.urls', namespace='ManageProduct')),
    path('ManageStore/', include('ManageStore.urls', namespace='ManageStore')),
    path('ManageOffer/', include('ManageOffer.urls', namespace='ManageOffer')),
    path('ManageReview/', include('ManageReview.urls', namespace='ManageReview')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'Dashboard.views.error_404'

ManageStore/models.py
import datetime

from django.db import models
from django.utils.text import slugify
from phonenumber_field.modelfields import PhoneNumberField

from ManageOffer.models import Offer
from ManageProduct.models import Product
from ManageReview.models import Review

STORE_TYPE = (
    ('HyperMarket', 'HyperMarket'),
    ('BigMarket', 'BigMarket')
)


class Section(models.Model):
    name = models.CharField(max_length=20, blank=True)

    def __str__(self):
        return str(self.name)


class AD_imags(models.Model):

    def AD_imags_directory_path(instance, filename):
        return 'AD_imags/{0}/{1}'.format(instance.name, filename)

    name = models.CharField(max_length=50)
    ad_imags = models.ImageField(upload_to=AD_imags_directory_path, default='AD default.png')


class Store(models.Model):
    def store_directory_path(instance, filename):
        return 'Store/{0}-{1}'.format((instance.name, instance.id), filename)

    sections = models.ManyToManyField(Section, blank=True)
    slug = models.SlugField(blank=True, null=True)
    name = models.CharField(max_length=50, unique=True, null=False)
    image = models.ImageField(upload_to=store_directory_path, default='store default.jpg')
    phonesNumber = PhoneNumberField(null=True, blank=True, unique=True,
                                    help_text='Phone number must be entered in the format \'+999999999\'. Up to 15 digits allowed.')
    type = models.CharField(max_length=50, choices=STORE_TYPE, default='HyperMarket')
    url = models.URLField(max_length=200, blank=True, unique=True, null=True)
    description = models.TextField(max_length=500, blank=True, null=True)
    start_hours = models.TimeField(max_length=50, blank=True, null=True)
    close_hours = models.TimeField(max_length=50, blank=True, null=True)
    state = models.BooleanField(default=True, blank=True)
    join_at = models.DateField(null=True, blank=True)
    products = models.ManyToManyField(Product, blank=True)
    StoreReviews = models.ManyToManyField(Review, blank=True)
    StoreOffers = models.ManyToManyField(Offer, blank=True)
    new = models.BooleanField(default=True, null=False)
    ADs = models.ManyToManyField(AD_imags)

    def get_ADs_id(self):
        IDs = []
        for ad in self.ADs.all():
            IDs.append(ad.id)
        return IDs

    def save(self, *args, **kwargs):
        if not self.name:
            self.name = ('NO NAME {0}'.format(datetime.datetime.now()))
        if not self.slug:
            self.slug = slugify(self.name)
        # if not self.ADs:
        #     self.ADs= AD_imags.objects.create(mane='{0}-{1}'.format(self.name,self.id))
        super(Store, self).save(*args, **kwargs)

    @property
    def is_open_now(self):
        if (self.close_hours and self.start_hours) is not None:
            now = datetime.datetime.now().time()
            self.state = self.start_hours <= now <= self.close_hours
            return self.state

    def __str__(self):
        self.is_open_now
        return str(self.name)

    @property
    def Average(self):
        if self.StoreReviews.all():
            revs = self.StoreReviews.all()
            total = 0
            for x in revs:
                total += x.rating
            return total / len(revs)
        else:
            return 0

    def get_sections(self):
        return self.sections.all()

    def is_sections_exist(self, sec):
        for name in self.sections.all():
            if name.name == sec:
                return True
        return False

    def add_sections(self, new_sections):
        sec = Section(name=new_sections)
        sec.save()
        self.sections.add(sec)
        self.save()

ManageStore/forms.py
from django import forms

from ManageStore.models import Store, AD_imags


class CreateStoreForm(forms.ModelForm):
    class Meta:
        model = Store
        fields = [
            'name',
            'image',
            'phonesNumber',
            'start_hours',
            'close_hours',
            'description',
            'state',
            'type',
            'url',
        ]


class EditStoreForm(forms.ModelForm):
    new_sections = forms.CharField(label='Add new product_sections', required=False, )

    class Meta:
        model = Store
        fields = [
            'name',
            'image',
            'phonesNumber',
            'start_hours',
            'close_hours',
            'description',
            'state',
            'type',
            'url',
            'new_sections']


class ADForm(forms.ModelForm):
    class Meta():
        model= AD_imags
        fields=['ad_imags']

ManageStore/views.py
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, get_object_or_404, render

from ManageStore.forms import EditStoreForm, CreateStoreForm
from ManageStore.models import Store, AD_imags, Section
from accounts.models import StoreAdminProfile


def view_store(request, store_id ):
    store = get_object_or_404(Store, id=store_id)
    sec= store.sections.all()
    products = store.products.all()
    ads = store.ADs.all()
    context = {
        'store': store,
        'products': products,
        'ads': ads,
        'sec':sec,
    }
    return render(request, 'store.html', context)


def create_store(request):
    user = get_object_or_404(StoreAdminProfile, user=request.user)
    store_form = CreateStoreForm(request.POST or None, request.FILES)
    if request.method == 'POST':
        if store_form.is_valid():
            new_store = store_form.instance
            new_store.save()
            user.set_store(new_store.pk)
            return redirect('/')
    else:
        store_form = CreateStoreForm()
    context = {'form': store_form}
    return render(request, 'Create_Store.html', context)


def edit_store(request):
    user = get_object_or_404(StoreAdminProfile, user=request.user)
    store = get_object_or_404(Store, id=user.store.id)
    if request.method == 'POST':
        form = EditStoreForm(request.POST or None, request.FILES or None, instance=store)
        if form.is_valid():
            sec = form.cleaned_data.get('new_sections')
        if store.is_sections_exist(sec):
            messages.warning(request, 'This Section Is exist')
        elif str(sec) != '':
            store.add_sections(sec)
        else:
            store = form.instance
            store.save()
        return redirect('ManageStore:view_store', store.id)  # Redirect change
    else:
        form = EditStoreForm(instance=store)
    return render(request, 'edit_store.html', {'form': form})


def delete_ADs(request,ad_id):
    user = get_object_or_404(StoreAdminProfile, user=request.user)
    store = get_object_or_404(Store, id=user.store.id)
    ad= get_object_or_404(AD_imags ,id = ad_id)
    if request.method == 'POST':
        if store.ADs.get(id=ad.id):
            ad.delete()
            messages.warning(request, "AD Can't Delete  ")
        else:
            messages.warning(request,"AD Can't Delete  ")
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def add_ADs(request):
    user = get_object_or_404(StoreAdminProfile, user=request.user)
    store = get_object_or_404(Store, id=user.store.id)

    if request.method == 'POST':
        new_AD = AD_imags()
        new_AD.name = store.name
        new_AD.ad_imags = request.FILES['ad_imags']
        new_AD.save()
        store.ADs.add(new_AD)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def products_in_section(request, store_id, section):
    store = get_object_or_404(Store, id=store_id)
    products=store.products.filter(product_sections=section)
    sec = store.sections.all()
    ads = store.ADs.all()
    context = {
        'store': store,
        'products': products,
        'ads': ads,
        'sec': sec,
    }
    return render(request, 'store.html', context)

ManageStore/templates/Create_Store.html
{% extends "base.html" %}
{% load bootstrap5 %}

{% block content %}
    <title>Create Store</title>

    <div class="container">
        <form action="" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" value="Save" class="default" name="_save">
        </form>
    </div>
{% endblock %}

ManageStore/templates/Store_card_info.html
{% block store_card %}
    <div class="card ">
        <a href="{% url 'ManageStore:view_store' store.id %}">
            <img src="{{ store.image.url }}"
                 class="img-fluid" alt=""   style="min-height: 150px;min-width:279px;max-height: 150px;max-width:280px"
            ></a>
        <div class="card-body">
            <a href="{% url 'ManageStore:view_store' store.id %}"><h5 class="card-title">{{ store.name|slice:"20" }}</h5></a>
            {% if store.is_open_now %}
                <p class="card-text">
                    <small class="text-muted"> Hours works {{ store.start_hours }} TO {{ store.close_hours }} </small><br>
                    <small class="text-muted"><b style="color: #28a745">Open</b>
                        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor"
                             class="bi bi-door-open " viewBox="0 0 16 16" style="color: #28a745">
                            <path d="M8.5 10c-.276 0-.5-.448-.5-1s.224-1 .5-1 .5.448.5 1-.224 1-.5 1z"/>
                            <path d="M10.828.122A.5.5 0 0 1 11 .5V1h.5A1.5 1.5 0 0 1 13 2.5V15h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V1.5a.5.5 0 0 1 .43-.495l7-1a.5.5 0 0 1 .398.117zM11.5 2H11v13h1V2.5a.5.5 0 0 0-.5-.5zM4 1.934V15h6V1.077l-6 .857z"/>
                        </svg>
                    </small>
                </p>
            {% else %}
                <p class="card-text">
                    <small class="text"> Hours works {{ store.start_hours }}TO {{ store.close_hours }} </small>
                    <small class="text-muted" ><b style="color: #ff0018">Close</b>
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-door-open-fill" viewBox="0 0 16 16" style="color: #ff001b">
                            <path d="M1.5 15a.5.5 0 0 0 0 1h13a.5.5 0 0 0 0-1H13V2.5A1.5 1.5 0 0 0 11.5 1H11V.5a.5.5 0 0 0-.57-.495l-7 1A.5.5 0 0 0 3 1.5V15H1.5zM11 2h.5a.5.5 0 0 1 .5.5V15h-1V2zm-2.5 8c-.276 0-.5-.448-.5-1s.224-1 .5-1 .5.448.5 1-.224 1-.5 1z"/>
                        </svg>
                    </small>
                </p>
            {% endif %}
        </div>
    </div>
{% endblock store_card %}

ManageStore/templates/Store_services.html
{% block Store_services %}
    <div>


        <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
            <!--Product's -->
            <li class="nav-item" role="presentation">
                <a class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" href="#pills-home" role="tab"
                   aria-controls="pills-home" aria-selected="true">Product's</a>
            </li>
            <!--Offer's -->
            <li class="nav-item" role="presentation">
                <a class="nav-link" id="pills-Offer-tab" data-bs-toggle="pill" href="#pills-Offer" role="tab"
                   aria-controls="pills-Offer" aria-selected="false">Offer's</a>
            </li>
            <!--AD image's -->
            <li class="nav-item" role="presentation">
                <a class="nav-link" id="pills-ADs-tab" data-bs-toggle="pill" href="#pills-ADs" role="tab"
                   aria-controls="pills-ADs" aria-selected="false">AD image's</a>
            </li>
            <!--My Review  -->
            <li class="nav-item" role="presentation">
                <a class="nav-link" id="pills-Review-tab" data-bs-toggle="pill" href="#pills-Review" role="tab"
                   aria-controls="pills-Review" aria-selected="false">My Review</a>
            </li>
            <li>
                            <a href="{% url 'ManageStore:edit_store'%}" class="btn bg-warning">Edit Store info </a>

            </li>

        </ul>
        <div class="tab-content" id="pills-tabContent">
            <!--Product's -->
            <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
                {% block product_table %}
                    {% include 'products_table.html' with products=store.products.all %}
                {% endblock product_table %}
            </div>
            <!--Offer's -->
            <div class="tab-pane fade" id="pills-Offer" role="tabpanel" aria-labelledby="pills-Offer-tab">
                {% block offer_table %}
                    {% include 'offers_table.html' with offers=store.StoreOffers.all %}
                {% endblock offer_table %}
            </div>
            <!--AD image's -->
            <div class="tab-pane fade" id="pills-ADs" role="tabpanel" aria-labelledby="pills-ADs-tab">
                {% block add_ads %}
                    {% include 'add_ADs.html' with store=store form=form%}
                {% endblock add_ads %}
            </div>
            <!--My Review  -->
            <div class="tab-pane fade" id="pills-Review" role="tabpanel" aria-labelledby="pills-Review-tab">
                {% block reviews_table %}
                    {% include 'reviews_table.html' with reviews=store.StoreReviews.all %}
                {% endblock reviews_table %}
            </div>
        </div>


    </div>
{% endblock Store_services %}

ManageStore/templates/StoresADslide.html
{% block StoresADslide %}
    {% if ads %}
        <div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="{{ ads.first.ad_imags.url }}" class="d-block" alt="..."
                         style="min-height:300px;min-width:100%;max-height: 300px;max-width:100% ">
                </div>
                {% for ad in ads %}
                    <div class="carousel-item">
                        <img src="{{ ad.ad_imags.url }}" class="d-block" alt="..."
                             style="min-height:300px;min-width:100%;max-height: 300px;max-width:100% ">
                    </div>
                {% endfor %}
            </div>

            <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </a>
        </div>

    {% else %}
        <div class="carousel-item active">
            <img src="http://placehold.it/900x350" class="d-block" alt="..."
                 style="min-height:300px;min-width:100%;max-height: 300px;max-width:100% ">
        </div>

    {% endif %}

{% endblock StoresADslide %}

ManageStore/templates/add_ADs.html
{% load bootstrap5 %}
{% block add_ads %}
    <div class="container-fluid">
        <div class="row">
            {% for ad in store.ADs.all %}

                <div class="col-3" style="padding-left: 5px">
                    <form action="{% url 'ManageStore:delete_ADs' ad.id %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <img src="{{ ad.ad_imags.url }}" height="200px" width="200px" border="2" >
                            <button type="submit" class="btn btn-danger" >Delete</button>
                        </div>
                    </form>
                </div>
            {% endfor %}
        </div>
        <div class="row">
            <div class="col-12">

                <form action="{% url 'ManageStore:add_ADs' %} " enctype="multipart/form-data" method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                   <br> <button type="submit" class="btn btn-success">Upload</button>
                </form>

            </div>
        </div>
    </div>
{% endblock add_ads %}

ManageStore/templates/edit_store.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
    <title>Edit Store</title>

    <div class="container">
    <form action="" enctype="multipart/form-data" method="post">

        {% csrf_token %}
        {% bootstrap_form form %}
        <br><input type="submit" value="Save" class="default" name="_save">

    </form>
 </div>
{% endblock %}

ManageStore/templates/store.html
{% extends 'base.html' %}
{% block content %}
        <title>Store Detail</title>
    <div class="container">
        {% block Store %}

            <div class="row">
                <div class="col-3">
                    {% block PostNewReview %}
                        {% include 'PostNewReview.html' with form=form TO='ManageReview:add-store-review' id=store.id %}
                    {% endblock PostNewReview %}

                    {% for review in store.StoreReviews.all %}
                        {% block review_card %}
                            {% include 'review_card.html' with review=review %}
                        {% endblock review_card %}
                    {% endfor %}
                </div>

                <div class=" col-9">
                <div class="row" style="margin:5px">
{#                    {% block sections %}#}
{#                       {% include 'sections.html' with sections=store.sections.all %}#}
{#                    {% endblock sections %}#}
                    {% for s in sec %}

                     <a href="{% url 'ManageStore:view_store_section' store.id s.name %}" class="btn bg-primary col-1" style="margin-left: 5px">
                        {{ s.name|slice:'10' }}</a>
                    {% endfor %}


                </div>

                    <div class="row">

                        {% block StoresADslide %}
                            {% include 'StoresADslide.html' with ad=ads %}
                        {% endblock StoresADslide %}
                    </div>
                    <div class="row row-cols-1 row-cols-md-3 g-4">
                        {% for product in products %}

                            {% include 'product_in_squre_card.html' with product=product %}

                        {% endfor %}

                    </div>
                </div>
            </div>
        {% endblock Store %}

    </div>

{% endblock content %}

ManageStore/templates/stores_in_squre_card.html
{% block Store %}
        <div class="container">
            <div class="row">
                <div class="card-group">
                    {% for store in Stores %}
                        {% include 'Store_card_info.html' with store=store %}
                        {% empty %}
                        <h1 > the ar no store join </h1>
                    {% endfor %}
                </div>
            </div>
        </div>
{% endblock Store %}